# Generated by Django 5.1.6 on 2025-02-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
    ]
